<blockquote>
  <p>
    <strong>Sayın</strong>, %Adi% %Soyadi%
    <br />
    <strong>&Uuml;yeliğinizi aktif etmek i&ccedil;in aşağıdaki bağantıyı tıklayınız.</strong>
    <br />
    Aktivasyon işleminizi ger&ccedil;ekleştirmek i&ccedil;in&nbsp;<a title="Aktivason işlemi i&ccedil;in buraya tıklayınız." href="%SiteUrl%?l=account&amp;r=aktivasyon&amp;g=%ID%&amp;s=%OnayKodu%">buraya tıklaynız.</a>
    <br />
    <br />
    <strong>Alternatif link &uuml;steki link &ccedil;alışmıyorsa aşağıdaki bağlantıyı tarayıcınızın adres çubuğuna yapıştırınız ve adrese gidiniz.</strong><br />
    <br />
    %SiteUrl%?l=4&amp;r=aktivasyon&amp;g=%ID%&amp;s=%OnayKodu%
    <br />
    <br />
    <br />
    <hr />
    <strong>
      <em>%SiteTitle% </em>
    </strong><em>
      <strong>Site Y&ouml;netimi</strong>
    </em>
  </p>
</blockquote>