<div id="card-view">
    <ul>
      <li class="title">
        <img class="icons" src="/images/icons/16/home.png" />%Kurum%
      </li>
      <li>
        <h1>
          <img src="/images/icons/10/phone.png" />Telefon
        </h1>
        <span>:</span>
        <div>
          %Telefon%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          <img src="/images/icons/10/mail.png" />Adres
        </h1>
        <span>:</span>
        <div>
          %Adres%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          <img src="/images/icons/10/work.png" />İlçe/Semt
        </h1>
        <span>:</span>
        <div>
          %Semt%/%Sehir%
        </div>
        <div class="clear">
        </div>
      </li>
    </ul>
    <div class="clear">
    &nbsp;
    </div>
</div>