<div id="page-view">
  <div class="title">
    <h1 class="left">
      <a href="%Url%" class="toolTip" title="Hastane Anasayfasına Git">%HastaneAdi%</a>
    </h1>
    <div class="info right">
      <span class="toolTip" style="cursor:pointer;" title="Bu oran hastanenin tekil izlenme sayısını gösterir.">
        PR:&nbsp;<b>%Gosterim%</b>
      </span>
    </div>
    <div class="clear">
    </div>
  </div>
  <div class="profil">
    <img src="%ResimUrl%" alt="%Adi% %Soyadi%" class="image left" />
    <ul class="info right">
      <li>
        <h1>
          Uzmanlık Alanı
        </h1>
        <span>:</span>
        <div>
          %UzmanlikAlani%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          Telefon
        </h1>
        <span>:</span>
        <div>
          %Telefon%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          Adres
        </h1>
        <span>:</span>
        <div>
          %Adres%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          İlçe/Semt
        </h1>
        <span>:</span>
        <div>
          %Semt%/%Sehir%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          E-Posta
        </h1>
        <span>:</span>
        <div>
          %Mail%
        </div>
        <div class="clear">
        </div>
      </li>
      <li>
        <h1>
          Web Sitesi
        </h1>
        <span>:</span>
        <div>
          %WebSitesi%
        </div>
        <div class="clear">
        </div>
      </li>
    </ul>
    <div class="clear">
    </div>
    <div class="menu">
      <a href="%Iletisim%">
        <img class="first" src="%ImagesPath%hastaneye-ulasin.png" alt="Hastaneye Ulaşın" />
      </a>
      <a href="%Makaleleri%">
        <img src="%ImagesPath%tum-yazilari.png" alt="Tüm Yazıları" />
      </a>
      <a href="%Mesajlari%">
        <img src="%ImagesPath%cevapladigi-sorular.png" alt="Cevapladığı Sorular" />
      </a>
      <a href="%YazarHakkinda%">
        <img src="%ImagesPath%hastane-hakkindaki-gorusler.png" alt="Hastane Hakkındaki Görüşler" />
      </a>
      %RandevuAl%
    </div>
    <div class="clear">
    </div>
  </div>
</div>