<div class="top-link right">
    (<a href="%VirtualPath%logout">Çıkış</a>)
</div>
Hoşgeldiniz Sayın,&nbsp;<div class="top-link right">
%Adi%&nbsp;%Soyadi%&nbsp;%toplamSayi%
<div class="contextMenu">
        <ul>
            <li><a href="%VirtualPath%%Url%"><img src="%VirtualPath%images/icons/menu/global.png" />Başkasının Gözünden</a></li>
            <li><a href="%VirtualPath%hesabim"><img src="%VirtualPath%images/icons/menu/settings.png" />Hesap Ayarları</a></li>
            <li><a href="%VirtualPath%harita"><img src="%VirtualPath%images/icons/menu/arrow.png" />Haritadaki Konum</a></li>
            <li%randevutalepleriCss%><a href="%VirtualPath%%randevutalepleriQuery%"><img src="%VirtualPath%images/icons/menu/calendar.png" />Randevu Talepleri %randevutalepleri%</a></li>
            <li%randevularimCss%><a href="%VirtualPath%randevularim"><img src="%VirtualPath%images/icons/menu/time.png" />Randevularımız %randevularim%</a></li>
            <li%sorulanlarCss%><a href="%VirtualPath%%sorulanlarQuery%"><img src="%VirtualPath%images/icons/menu/mail.png" />Gelen Sorularımız %sorulanlar%</a></li>
            <li%sorduklarimCss%><a href="%VirtualPath%sorduklarim"><img src="%VirtualPath%images/icons/menu/question.png" />Sorduğumuz Sorularımız %sorduklarim%</a></li>
            <li%yorumlanlarCss%><a href="%VirtualPath%%yorumlanlarQuery%"><img src="%VirtualPath%images/icons/menu/comments.png" />Gelen Yorumlarımız %yorumlanlar%</a></li>
            <li%yorumlarimCss%><a href="%VirtualPath%yorumlarim"><img src="%VirtualPath%images/icons/menu/mycomment.png" />Yazdığımız Yorumlar %yorumlarim%</a></li>
            <li class="user-panel"><a href="%VirtualPath%yenimakale"><img src="%VirtualPath%images/icons/menu/page.png" />Yeni Makale Yaz</a></li>
            <li><a href="%VirtualPath%makalelerim"><img src="%VirtualPath%images/icons/menu/arrow.png" />Yazılan Makaleler</a></li>
            <li class="user-panel"><a href="%VirtualPath%yenivideo"><img src="%VirtualPath%images/icons/menu/movie.png" />Yeni Video Ekle</a></li>
            <li><a href="%VirtualPath%videolarim"><img src="%VirtualPath%images/icons/menu/arrow.png" />Eklenen Videolar</a></li>
        </ul>
    </div>
</div>