<div class="top-link right">
    (<a href="%VirtualPath%logout">Çıkış</a>)
</div>
Hoşgeldiniz Sayın, <div class="top-link right">
  %Adi%&nbsp;%Soyadi%&nbsp;%toplamSayi%
  <div class="contextMenu">
        <ul>
            <li><a href="%VirtualPath%hesabim"><img src="%VirtualPath%images/icons/menu/settings.png" />Hesap Ayarları</a></li>
            <li%randevularimCss%><a href="%VirtualPath%randevularim"><img src="%VirtualPath%images/icons/menu/time.png" />Randevularım %randevularim%</a></li>
            <li%sorduklarimCss%><a href="%VirtualPath%sorduklarim"><img src="%VirtualPath%images/icons/menu/question.png" />Sorduğum Sorular %sorduklarim%</a></li>
            <li%yorumlarimCss%><a href="%VirtualPath%yorumlarim"><img src="%VirtualPath%images/icons/menu/mycomment.png" />Yazdığım Yorumlar %yorumlarim%</a></li>
            <li class="admin-panel"><a href="%VirtualPath%panel/"><img src="%VirtualPath%images/icons/menu/key.png" />Yönetim Paneli</a></li>
            <li%hesaplarCss%><a href="%VirtualPath%panel/?go=hesapliste%hesaplarQuery%"><img src="%VirtualPath%images/icons/menu/settings.png" />Hesap Yönetimi %hesaplar%</a></li>
            <li%randevularCss%><a href="%VirtualPath%panel/?go=randevuliste%randevularQuery%"><img src="%VirtualPath%images/icons/menu/calendar.png" />Randevu Yönetimi %randevular%</a></li>
            <li%sorularCss%><a href="%VirtualPath%panel/?go=mesajliste%sorularQuery%"><img src="%VirtualPath%images/icons/menu/mail.png" />Soru Yönetimi %sorular%</a></li>
            <li%yorumlarCss%><a href="%VirtualPath%panel/?go=yorumliste%yorumlarQuery%"><img src="%VirtualPath%images/icons/menu/comments.png" />Yorum Yönetimi %yorumlar%</a></li>
            <li><a href="%VirtualPath%panel/?go=reklamliste"><img src="%VirtualPath%images/icons/menu/page.png" />Reklam Yönetimi</a></li>
        </ul>
    </div>
</div>