<div class="top-link right">
    (<a href="%VirtualPath%logout">Çıkış</a>)
</div>
Hoşgeldiniz Sayın, <div class="top-link right">
%Adi%&nbsp;%Soyadi%&nbsp;%toplamSayi%
<div class="contextMenu">
        <ul>
            <li><a href="%VirtualPath%hesabim"><img src="%VirtualPath%images/icons/menu/settings.png" />Hesap Ayarları</a></li>
            <li%randevularimCss%><a href="%VirtualPath%randevularim"><img src="%VirtualPath%images/icons/menu/calendar.png" />Randevu Taleplerim %randevularim%</a></li>
            <li%sorduklarimCss%><a href="%VirtualPath%sorduklarim"><img src="%VirtualPath%images/icons/menu/users.png" />Sorduğum Sorular %sorduklarim%</a></li>
            <li%yorumlarimCss%><a href="%VirtualPath%yorumlarim"><img src="%VirtualPath%images/icons/menu/mycomment.png" />Yazdığım Yorumlar %yorumlarim%</a></li>
        </ul>
    </div>
</div>