<div class="top-link right">
    Yeni Üyelik
    <div class="contextMenu context-last">
        <ul>
            <li><a href="%VirtualPath%?l=2&type=standart"><img src="%VirtualPath%images/icons/menu/global.png" />Standart Üye Formu</a></li>
            <li><a href="%VirtualPath%?l=2&type=editor"><img src="%VirtualPath%images/icons/menu/users.png" />Doktor Başvuru Formu</a></li>
            <li><a href="%VirtualPath%?l=2&type=moderator"><img src="%VirtualPath%images/icons/menu/work.png" />Merkez Kayıt Formu</a></li>
        </ul>
    </div>
</div>
<div class="top-link right">
    <a href="%VirtualPath%login">Üye Girişi</a>&nbsp;&nbsp;&nbsp;-
</div>