<div id="page-view">
  <div class="title">
    <h1 class="left">
      %Baslik%
    </h1>
    <div class="social right">
      <div class="addthis_toolbox">
        <div class="custom_images">
          <a class="addthis_button_facebook">
            <img class="toolTip" src="%ImagesPath%facebook.png" alt="Share to Facebook" border="0" />
          </a>
          <a class="addthis_button_twitter">
            <img class="toolTip" src="%ImagesPath%twitter.png" border="0" alt="Share to Twitter" />
          </a>
        </div>
      </div>
    </div>
    <div class="clear">
    </div>
  </div>
  <div class="text">
    %ResimUrl%<span class="description">%Ozet%&nbsp;</span>%Icerik%
    <div class="clear">
      &nbsp;
    </div>
    <h1 style="margin-top: 5px;margin-bottom: 3px;font-weight:normal;">
      <img class="left" style="margin-right: 3px;" src="%ImagesPath%icons/12/editor.png" border="0" />Editör Bilgileri;
    </h1>
    <p style="margin-bottom: 5px;display:block;font-size=16px;">
      <a href="%Url%" target="_blank">
        <b class="left">%Unvan%%Adi% %Soyadi%</b>
        <img class="toolTip left" style="margin-left: 3px;" src="%ImagesPath%icons/10/expand.png" title="%Adi% %Soyadi% sayfasına git." alt="Yazarın sayfasına git." border="0" />
        <div class="clear">
        </div>
      </a>
    </p>
    <p style="display:block;">
      <b>%UzmanlikAlani%</b>
    </p>
    <div class="clear">
    </div>
  </div>
  <div class="footer">
    <div class="social left">
      <!-- AddThis Button BEGIN -->
      <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
        <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
      </div>
      <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=baymyo"></script>
      <!-- AddThis Button END -->
    </div>
    <span class="info right">
      Bu %ModulID% <b class="toolTip" style="cursor:pointer;" title="Bu oran %ModulID% tekil izlenme sayısını gösterir.">%Gosterim%</b> kere okundu.
    </span>
    <div class="clear">
    </div>
  </div>
</div>