<div class="details-block">
    <div class="cbHeader">
    <div class="tL left">
        <span class="title">
        <b>Doktor</b> Hakkında
        </span>
    </div>
    <div class="tR right">
    </div>
    <div class="clear">
    </div>
    </div>
    <div class="cbBody">
    <div class="cbContainer" style="text-align: justify">
        %Hakkimda%
    </div>
    </div>
    <div class="cbFooter">
    </div>
</div>